version: "3.8"

# just run "(sudo) docker compose up" to start the containers

services:
  node1: 
    image: rahulbaradol/clock-node
    container_name: node1
    ports:
      - "8080:3000"
    environment:
      - PROC_ID=1
      - NODE_NAME=node1
      - LIST_OF_NODES=node1,node2,node3
      - PYTHONUNBUFFERED=1

  node2:
    image: rahulbaradol/clock-node
    container_name: node2
    ports:
      - "8081:3000"
    environment:
      - PROC_ID=2
      - NODE_NAME=node2
      - LIST_OF_NODES=node1,node2,node3
      - PYTHONUNBUFFERED=1

  node3:
    image: rahulbaradol/clock-node
    container_name: node3
    ports:
      - "8082:3000"
    environment:
      - PROC_ID=3
      - NODE_NAME=node3
      - LIST_OF_NODES=node1,node2,node3
      - PYTHONUNBUFFERED=1